name=CITestLibrary
version=1.0.0
author=Dave Harris
maintainer=Dave Harris
sentence=A sandbox library to test GitHub Actions and PlatformIO.
paragraph=This is a minimal framework designed to practice continuous integration.
category=Signal Input/Output
url=https://github.com
architectures=*
