[platformio]
# Force PlatformIO to look at your Arduino IDE style paths
lib_extra_dirs = .
src_dir = examples/BasicUsage

[env]
framework = arduino

# --- Test 1: The classic 8-bit Uno ---
[env:uno]
platform = atmelavr
board = uno

# --- Test 2: The 32-bit ESP32 ---
[env:esp32]
platform = espressif32
board = esp32dev  <-- Change this line right here!
