[platformio]
# Tell PlatformIO that your core library source code lives inside 'src'
lib_dir = src
# Tell PlatformIO where to look for the sketch file to compile
src_dir = examples/BasicUsage

[env]
framework = arduino

# --- Test 1: The classic 8-bit Uno ---
[env:uno]
platform = atmelavr
board = uno

# --- Test 2: The 32-bit ESP32 ---
[env:esp32]
platform = espressif32
board = esp32dev
