name: Arduino Native Test Build

on: [push, pull_request]

jobs:
  build:
    name: Compile for ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: "arduino:avr:uno"
            name: "Arduino Uno (AVR)"
          - board: "arduino:avr:nano"
            name: "Arduino Nano (AVR)"
          - board: "esp32:esp32:esp32"
            name: "ESP32 Dev Module"
          - board: "esp32:esp32:esp32s3"
            name: "ESP32-S3 DevKit"
          - board: "esp32:esp32:esp32c3"
            name: "ESP32-C3 DevKit"
          - board: "esp32:esp32:esp32c6"
            name: "ESP32-C6 DevKit"
          - board: "STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F401RE"
            name: "STM32 Native CAN"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Compile Library Examples
      uses: arduino/compile-sketches@v1
      with:
        fqbn: ${{ matrix.board }}
        sketch-paths: examples/BasicUsage
        platforms: |
          - name: "esp32:esp32"
            source-url: "https://githubusercontent.com"
          - name: "STMicroelectronics:stm32"
            source-url: "https://github.com"
