name: Arduino Native Test Build

on: [push, pull_request]

jobs:
  build-all-boards:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Configure Core Registries
      env:
        ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json https://github.com"
      run: arduino-cli core update-index

    - name: Install Toolchain Platforms
      env:
        ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json https://github.com"
      run: |
        arduino-cli core install arduino:avr
        arduino-cli core install esp32:esp32
        arduino-cli core install STMicroelectronics:stm32

    - name: Compile Library Examples
      run: |
        arduino-cli compile --library "." --fqbn arduino:avr:uno ./examples/BasicUsage
        arduino-cli compile --library "." --fqbn arduino:avr:nano ./examples/BasicUsage
        arduino-cli compile --library "." --fqbn esp32:esp32:esp32 ./examples/BasicUsage
        arduino-cli compile --library "." --fqbn esp32:esp32:esp32s3 ./examples/BasicUsage
        arduino-cli compile --library "." --fqbn esp32:esp32:esp32c3 ./examples/BasicUsage
        arduino-cli compile --library "." --fqbn esp32:esp32:esp32c6 ./examples/BasicUsage
        arduino-cli compile --library "." --fqbn STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F401RE ./examples/BasicUsage
